sudo: required
language: bash
build_pojeb:
  before_install:
    - sudo dpkg --add-architecture i386
  install:
    - wget
    - xvfb
    - wine
    - winetricks
    - unzip
  script:
    - wget -O - https://github.com/smok-serwis/pojeb/raw/master/jebac-to | sudo bash
    - mkdir vagrant-tibbo-build
    - cp Vagrantfile misc/tibbo_build.sh misc/pojeb.sh vagrant-tibbo-build
    - zajeb vagrant-tibbo-build
    - dojeb vagrant-tibbo-build.jeb
